default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: approva_test_development

test:
  <<: *default
  database: approva_test_test

production:
  <<: *default
  database: approva_test_production
  username: approva_test
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
