default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  encoding: unicode
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  database: approva_test_development
  pool: 5

test:
  <<: *default
  database: approva_test_test

docker:
  encoding: unicode
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  database: approva_test_development
  pool: 5

production:
  <<: *default
  database: approva_test_production
  username: approva_test
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
